### ISSUE TITLE
Erro ao criar projeto na area de trabalho:

### ISSUE THREAD

**Issue by LuizFer1** [brunoggdev/HefestosPHP#12]
Iniciei o projeto na area de trabalho no linux mint, onde o caminho era /home/user/Area de Trabalho/pasta/hefestos/project.
Ao tentar rodar `php forja iniciar` recebi o seguinte error:
![image](https://github.com/brunoggdev/HefestosPHP/assets/107441569/504e8c6b-1976-4a55-baa1-2f314776fcb6)
Ao meu ver o forja ou alguma outra configuração não reconhece diretorios com espaços, a solução foi apenas mover o projeto para a pasta documentos.

**Comment by brunoggdev** [comment]
Olá @LuizFer1, primeiramente muito obrigado por testar o Hefestos e obrigado também pelo feedback!

De fato consegui reproduzir o erro aqui e estou trabalhando em uma solução para o problema.

**Comment by brunoggdev** [comment]
Creio que o problema tenha sido solucionado e já está atualizado na branch main!
